---
apiVersion: v1
kind: Service
metadata:
  name: map-api
  labels:
    app: map-api
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: map-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: map-api-deployment
  labels:
    app: map-api
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: map-api
    spec:
      containers:
        - image: anthonyamanse/map-api:1.0
          name: map-api
          env:
            - name: MONGODB_URL
              value: ''
            - name: MONGODB_CERT_BASE64
              valueFrom:
                configMapKeyRef:
                  name: mongodb-cert
                  key: mongo.cert
          ports:
            - containerPort: 8080
